# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 23:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20161108_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 8, 20, 53, 3, 700502)),
        ),
    ]
