# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('departamento', models.SmallIntegerField(choices=[(1, 'VENDAS'), (2, 'ADMINISTRACAO'), (3, 'APOIO')])),
            ],
        ),
    ]
