# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.BigIntegerField(),
        ),
    ]
