# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convocacao',
            old_name='convocado',
            new_name='convocados',
        ),
    ]
