# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20170502_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.BigIntegerField(),
        ),
    ]
