# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_convocacao_pauta'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocacao',
            name='secretario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_secretario', to='pessoa.Pessoa'),
        ),
        migrations.AlterField(
            model_name='convocacao',
            name='presidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_presidente', to='pessoa.Pessoa'),
        ),
    ]
