# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_auto_20170508_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocacao',
            name='convocados',
            field=models.ManyToManyField(related_name='pessoa_convocados', to='pessoa.Pessoa'),
        ),
    ]
