# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doenca_Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Doenca')),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doenca_sintoma',
            name='fk_sintoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Sintoma'),
        ),
    ]
